on: [push]

steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: katyo/publish-crates@v2
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --all-features
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}